baseurl: '/centaurai'
exclude: ['README.md']
permalink: pretty
title: 'Centaur AI'

google_analytics_id: null
homepage:
  show_call_box: true
logo:
  mobile: "images/logo-mobile.svg"
  desktop: "images/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: '© 2020 - Centaur AI Startup'

seo:
  meta_og_title: "Centaur AI"
  meta_og_type: "website"
  meta_og_url: "https://centaurai.io"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "We are a startup that offers services of development, implementation and deployment of solutions based on Artificial Intelligence and Data Analysis in various fields: production, industry, renewable energies and goods."
  meta_twitter_card: "summary"
  meta_twitter_site: "@anasselhoud"
  meta_twitter_creator: "@anasselhoud"

collections:
  services:
    output: true
    permalink: /services/:path/
  team:
    output: true
    permalink: /team/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
